### ISSUE TITLE
Sync failed: RangeError: Invalid array length

### ISSUE THREAD

**Issue by SantaChains** [joshuakto/fit#136]
I encountered this issue, and since then, files haven't been syncing. What could be the cause? Is it due to too many folders and files or is it because the repository's PDF is too large?

**Comment by dbarnett** [comment]
I suspect it's the same issue #127 fixed (even though the error message mentioned there was slightly different).

If you want to use BRAT and update to the beta version (https://github.com/joshuakto/fit/discussions/138), it should already be fixed there.

**Comment by SantaChains** [comment]
I switched to the latest beta version of the plugin, but the error still appeared. It worked only after I removed the PDF file. I suspect the issue is related to the PDF file in the folder, as PDFs in the root directory can sync successfully.

**Comment by SantaChains** [comment]
[debug.log](https://github.com/user-attachments/files/23696607/debug.log)
